from datetime import datetime, timezone
from typing import Any, Dict, List

from app.schemas.contracts import PipelineInput


def extract(payload: PipelineInput) -> Dict[str, Any]:
    parsed = payload.parsed_text_chunks or [
        {"chunk_id": "chunk_1", "text": "Mock parsed chunk from uploaded financial document."}
    ]
    return {
        "extracted_facts": {
            "revenue": 10000000,
            "EBITDA": 1800000,
            "PAT": 900000,
            "total_debt": 3500000,
            "current_ratio": 1.3,
            "dscr": 1.2,
            "working_capital": 1400000,
            "contingent_liabilities": ["Corporate guarantee (mock)"],
            "related_party_transactions": ["Intercompany payable noted (mock)"],
            "auditor_remarks": ["No material qualification (mock)"],
            "extracted_entities": [
                {
                    "name": payload.company_details.company_name if payload.company_details else "Unknown Co",
                    "type": "company",
                    "role": "borrower",
                    "source_ref": "chunk_1",
                }
            ],
            "document_sources": [
                {"doc_id": "doc_1", "file_name": "mock.pdf", "section": "P&L", "page_ref": "p2"}
            ],
        },
        "parsed_text_chunks": parsed,
    }


def research(payload: PipelineInput) -> Dict[str, Any]:
    return {
        "risk_flags": [
            {
                "flag_id": "rf_mock_01",
                "flag_type": "financial",
                "severity": "medium",
                "description": "Leverage trend indicates moderate risk in mock analysis.",
                "evidence_refs": ["chunk_1"],
                "confidence": 0.66,
                "impact_on_score": "Moderate negative impact",
            }
        ]
    }


def score(payload: PipelineInput) -> Dict[str, Any]:
    return {
        "overall_score": 68.0,
        "score_breakdown": {
            "financial_strength": 70,
            "cash_flow": 66,
            "governance": 68,
            "contradiction_severity": 75,
            "secondary_research": 70,
            "officer_note": 70,
        },
        "decision": "review",
        "decision_explanation": "Overall score 68 in review band.",
        "recommended_limit": 2500000,
        "recommended_roi": 13.6,
        "reasons": ["Mock score fallback"],
    }


def generate_cam(payload: PipelineInput) -> Dict[str, Any]:
    case_id = payload.case_id or "case_unknown"
    return {
        "case_id": case_id,
        "final_decision": "approve_with_conditions",
        "recommended_limit": 2500000,
        "recommended_roi": 11.25,
        "key_reasons": [
            "Mock financial profile supports moderate lending exposure.",
            "Risk flags are present but manageable under conditions.",
        ],
        "evidence_summary": "Mock CAM output generated by placeholder pipeline.",
        "cam_doc_path": f"data/evidence/{case_id}/cam_mock.md",
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }

